# Generated by CodiumAI
from mlops.utils import load_config
import yaml
import pytest


class TestLoadConfig:
    # Loads a valid YAML config file successfully
    def test_load_valid_yaml_config_file(self):
        # Arrange
        config_path = "data\\valid_config.yml"

        # Act
        result = load_config(config_path)

        # Assert
        assert isinstance(result, dict)

    # Returns a dictionary object containing the loaded config
    def test_return_loaded_config(self):
        # Arrange
        config_path = "data\\valid_config.yml"

        # Act
        result = load_config(config_path)

        # Assert
        assert isinstance(result, dict)

    # Handles empty config files gracefully
    def test_handle_empty_config_files(self):
        # Arrange
        config_path = "data\\empty_config.yml"

        # Act
        result = load_config(config_path)

        # Assert
        assert isinstance(result, dict)

    # Raises a FileNotFoundError if the config file path is invalid
    def test_raise_file_not_found_error(self):
        # Arrange
        config_path = "data\\invalid_path.yml"

        # Act and Assert
        with pytest.raises(FileNotFoundError):
            load_config(config_path)

    # Raises a yaml.parser.ParserError if the config file is not a valid YAML file
    def test_raise_parser_error(self):
        # Arrange
        config_path = "data\\invalid_yaml_config.yml"

        # Act and Assert
        with pytest.raises(yaml.parser.ParserError):
            load_config(config_path)

    # Raises a TypeError if the config file is not a string
    def test_raise_type_error(self):
        # Arrange
        config_path = 123

        # Act and Assert
        with pytest.raises(TypeError):
            load_config(config_path)
