channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8.6
  - pip<=21.3.1
  - pip:
      - matplotlib==3.5.0
      - psutil==5.8.0
      - tqdm==4.62.0
      - pandas==1.3.0
      - scipy==1.7.0
      - numpy==1.21.0
      - ipykernel==6.0
      - azureml-core==1.51.0
      - azureml-defaults==1.51.0
      - azureml-mlflow==1.51.0
      - azureml-telemetry==1.51.0
      - azure-ai-ml==1.9.0
      - scikit-learn==1.0.0
      - debugpy==1.6.3
      - fsspec==2021.8.1
