[tool.mlops]
name = "mlops"
version = "0.1.1"
authors = [
  { name="", email="" },
]
description = "MLOPS libraries."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
